name: "ncf"
backend: "onnxruntime"
max_batch_size: 0

input [
  {
    name: "user_ids"
    data_type: TYPE_INT64
    dims: [-1]
  },
  {
    name: "item_ids"
    data_type: TYPE_INT64
    dims: [-1]
  }
]

output [
  {
    name: "scores"
    data_type: TYPE_FP32
    dims: [-1]
  }
]

instance_group [
  {
    kind: KIND_CPU
    count: 1
  }
]
